function compare_inversionsA(Nrun, Npop, Max_it)

clc;
close all;

if nargin < 1 || isempty(Nrun)
    Nrun = 5;
end

if nargin < 2 || isempty(Npop)
    Npop = 100;
end

if nargin < 3 || isempty(Max_it)
    Max_it = 50;
end

global n_mode
n_mode = 1;

fmin = 2;
df = 0.5;
fmax = 80;

freq = fmin:df:fmax;

VS_true = [200 250 300 400];
VP_true = [431 532 681 943];
H_true = [2 3 5];
den = [2000 2000 2000 2000];

pv_true = calcbase(freq, VS_true, H_true, VP_true, den);
pv_true = pv_true(:);

nD = 11;

lb = [ ...
    150 187.5 225 300 ...
    1.5 2.5 4.5 ...
    323.25 399 510.75 707.25];

ub = [ ...
    250 312.5 375 500 ...
    2.5 3.5 5.5 ...
    538.75 665 851.25 1178.75];

if any(ub < lb)
    error('Each upper bound must be greater than or equal to its lower bound.');
end

ct = 100:10:3000;
delta = 0.01;
jieshu = 1;

fitness_common = @(x) fitness( ...
    pv_true, ...
    4, ...
    x(1:4), ...
    x(5:7), ...
    x(8:11), ...
    den, ...
    freq, ...
    lb(1), ...
    ub(4));

algNames = { ...
    'WOA', ...
    'QPSO', ...
    'BWO', ...
    'SABO', ...
    'GOA', ...
    'ACOR', ...
    'Standard HHO', ...
    'DAEG-HHO'};

nAlg = numel(algNames);

Position_all = nan(Nrun, nD, nAlg);
Convergence_all = nan(Nrun, Max_it, nAlg);
FinalFitness_all = nan(Nrun, nAlg);

VsRMSE_all = nan(Nrun, nAlg);
VpRMSE_all = nan(Nrun, nAlg);
HRMSE_all = nan(Nrun, nAlg);

Leader_pos_all = nan(Nrun, nD);
Convergence_all_WOA = nan(Nrun, Max_it);

for run_idx = 1:Nrun

    [Leader_pos, ~, ~, Convergence_curve] = ...
        WOA_inversion( ...
        freq, ...
        VS_true, ...
        VP_true, ...
        H_true, ...
        den, ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub);

    Leader_pos = Leader_pos(:).';

    Leader_pos_all(run_idx, :) = Leader_pos;

    Convergence_all_WOA(run_idx, :) = ...
        fit_curve_length(Convergence_curve, Max_it);

    FinalFitness_all(run_idx, 1) = ...
        safe_objective(Leader_pos, fitness_common);
end

Position_all(:, :, 1) = Leader_pos_all;
Convergence_all(:, :, 1) = Convergence_all_WOA;

QPSO_all = nan(Nrun, nD);
Convergence_all_QPSO = nan(Nrun, Max_it);

for run_idx = 1:Nrun

    [~, xmin_i, histout] = ...
        QPSO_2_Adaptive_Improved( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        nD, ...
        fitness_common);

    xmin_i = xmin_i(:).';

    QPSO_all(run_idx, :) = xmin_i;

    Convergence_all_QPSO(run_idx, :) = ...
        fit_curve_length(histout, Max_it);

    FinalFitness_all(run_idx, 2) = ...
        safe_objective(xmin_i, fitness_common);
end

Position_all(:, :, 2) = QPSO_all;
Convergence_all(:, :, 2) = Convergence_all_QPSO;

VS_init = VS_true;
H_init = H_true;
VP_init = VP_true;

BWO_all = nan(Nrun, nD);
Curve_cell_BWO = cell(Nrun, 1);

for run_idx = 1:Nrun

    [xbest, ~, Curve] = ...
        BWO_inversion( ...
        freq, ...
        VS_init, ...
        H_init, ...
        VP_init, ...
        den, ...
        Npop, ...
        Max_it);

    xbest = xbest(:).';

    BWO_all(run_idx, :) = xbest;
    Curve_cell_BWO{run_idx} = Curve(:).';

    FinalFitness_all(run_idx, 3) = ...
        safe_objective(xbest, fitness_common);
end

Convergence_all_BWO = nan(Nrun, Max_it);

for run_idx = 1:Nrun

    Convergence_all_BWO(run_idx, :) = ...
        fit_curve_length(Curve_cell_BWO{run_idx}, Max_it);
end

Position_all(:, :, 3) = BWO_all;
Convergence_all(:, :, 3) = Convergence_all_BWO;

SABO_all = nan(Nrun, nD);
Convergence_all_SABO = nan(Nrun, Max_it);
pv_SABO = nan(numel(freq), 1);

try

    [sabo_out1, avg_pv2, sabo_out3, avg_SABO, ~] = ...
        SABO_inversion_VSH( ...
        freq, ...
        VS_true, ...
        VP_true, ...
        H_true, ...
        den, ...
        Npop, ...
        Max_it, ...
        Nrun, ...
        lb, ...
        ub, ...
        ct, ...
        delta, ...
        jieshu);

    if ismatrix(avg_pv2) && ...
            size(avg_pv2, 1) == numel(freq) && ...
            size(avg_pv2, 2) >= 1

        pv_SABO = avg_pv2(:, 1);

    elseif ismatrix(avg_pv2) && ...
            size(avg_pv2, 2) == numel(freq) && ...
            size(avg_pv2, 1) >= 1

        pv_SABO = avg_pv2(1, :).';

    elseif isvector(avg_pv2) && ...
            numel(avg_pv2) == numel(freq)

        pv_SABO = avg_pv2(:);

    elseif isvector(avg_pv2) && ...
            numel(avg_pv2) == 2 * numel(freq)

        pv_SABO = avg_pv2(1:numel(freq));
        pv_SABO = pv_SABO(:);

    else

        error( ...
            ['The SABO dispersion output has an unsupported size: ', ...
             '%s. The number of frequency samples is %d.'], ...
            mat2str(size(avg_pv2)), ...
            numel(freq));
    end

    Convergence_mean_SABO = ...
        fit_curve_length(avg_SABO, Max_it);

    for run_idx = 1:Nrun
        Convergence_all_SABO(run_idx, :) = ...
            Convergence_mean_SABO;
    end

    SABO_all = infer_sabo_positions( ...
        sabo_out1, ...
        sabo_out3, ...
        Nrun, ...
        nD);

    for run_idx = 1:Nrun

        FinalFitness_all(run_idx, 4) = ...
            safe_objective( ...
            SABO_all(run_idx, :), ...
            fitness_common);
    end

catch ME

    warning( ...
        'SABO failed or returned an incompatible output: %s', ...
        ME.message);
end

Position_all(:, :, 4) = SABO_all;
Convergence_all(:, :, 4) = Convergence_all_SABO;

GOA_all = nan(Nrun, nD);
Convergence_all_GOA = nan(Nrun, Max_it);

for run_idx = 1:Nrun

    [~, xmin_i, histout, ~, ~, ~] = ...
        GOA_AdaptiveA( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        nD, ...
        fitness_common);

    xmin_i = xmin_i(:).';

    GOA_all(run_idx, :) = xmin_i;

    Convergence_all_GOA(run_idx, :) = ...
        fit_curve_length(histout, Max_it);

    FinalFitness_all(run_idx, 5) = ...
        safe_objective(xmin_i, fitness_common);
end

Position_all(:, :, 5) = GOA_all;
Convergence_all(:, :, 5) = Convergence_all_GOA;

ACOR_all = nan(Nrun, nD);
Convergence_all_ACOR = nan(Nrun, Max_it);

for run_idx = 1:Nrun

    [best_x, ~, histout, ~, ~, ~] = ...
        ACOR_Adaptive( ...
        fitness_common, ...
        nD, ...
        lb, ...
        ub, ...
        Npop, ...
        5, ...
        1.5, ...
        0.5, ...
        Max_it, ...
        []);

    best_x = best_x(:).';

    ACOR_all(run_idx, :) = best_x;

    Convergence_all_ACOR(run_idx, :) = ...
        fit_curve_length(histout, Max_it);

    FinalFitness_all(run_idx, 6) = ...
        safe_objective(best_x, fitness_common);
end

Position_all(:, :, 6) = ACOR_all;
Convergence_all(:, :, 6) = Convergence_all_ACOR;

useParallel_HHO = true;

HHO_all = nan(Nrun, nD);
DAEG_all = nan(Nrun, nD);

Convergence_all_HHO = nan(Nrun, Max_it);
Convergence_all_DAEG = nan(Nrun, Max_it);

cfg_DAEG = struct( ...
    'useAdaptiveEJ', true, ...
    'useEliteGuidance', true, ...
    'useStagnationRepair', true);

for run_idx = 1:Nrun

    initialSeed = 5000 + run_idx;
    searchSeed = 15000 + run_idx;

    rng(initialSeed, 'twister');

    [f_best_hho, X_best_hho, hist_hho] = ...
        HHO_Rayleigh_Standard( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_common, ...
        useParallel_HHO, ...
        searchSeed);

    X_best_hho = X_best_hho(:).';

    HHO_all(run_idx, :) = X_best_hho;

    Convergence_all_HHO(run_idx, :) = ...
        fit_curve_length(hist_hho, Max_it);

    FinalFitness_all(run_idx, 7) = f_best_hho;

    rng(initialSeed, 'twister');

    [f_best_daeg, X_best_daeg, hist_daeg, ~] = ...
        HHO_Sobol_DAEG_Rayleigh( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_common, ...
        useParallel_HHO, ...
        searchSeed, ...
        cfg_DAEG);

    X_best_daeg = X_best_daeg(:).';

    DAEG_all(run_idx, :) = X_best_daeg;

    Convergence_all_DAEG(run_idx, :) = ...
        fit_curve_length(hist_daeg, Max_it);

    FinalFitness_all(run_idx, 8) = f_best_daeg;
end

Position_all(:, :, 7) = HHO_all;
Position_all(:, :, 8) = DAEG_all;

Convergence_all(:, :, 7) = Convergence_all_HHO;
Convergence_all(:, :, 8) = Convergence_all_DAEG;

for iAlg = 1:nAlg

    X_alg = Position_all(:, :, iAlg);

    VsRMSE_all(:, iAlg) = ...
        parameter_rmse(X_alg(:, 1:4), VS_true);

    HRMSE_all(:, iAlg) = ...
        parameter_rmse(X_alg(:, 5:7), H_true);

    VpRMSE_all(:, iAlg) = ...
        parameter_rmse(X_alg(:, 8:11), VP_true);
end

Convergence_mean = nan(nAlg, Max_it);
Position_mean = nan(nAlg, nD);

for iAlg = 1:nAlg

    Convergence_mean(iAlg, :) = ...
        mean_omitnan(Convergence_all(:, :, iAlg), 1);

    Position_mean(iAlg, :) = ...
        mean_omitnan(Position_all(:, :, iAlg), 1);
end

Dispersion_matrix = nan(numel(freq), nAlg);

for iAlg = 1:nAlg

    if iAlg == 4 && ...
            all(isnan(Position_mean(iAlg, :))) && ...
            any(isfinite(pv_SABO))

        Dispersion_matrix(:, iAlg) = pv_SABO(:);

    else

        Dispersion_matrix(:, iAlg) = ...
            safe_phase_curve( ...
            freq, ...
            Position_mean(iAlg, :), ...
            den);
    end
end

BestFitness = nan(nAlg, 1);
MeanFitness = nan(nAlg, 1);
MedianFitness = nan(nAlg, 1);
StdFitness = nan(nAlg, 1);
WorstFitness = nan(nAlg, 1);

VsMean = nan(nAlg, 1);
VsStd = nan(nAlg, 1);

VpMean = nan(nAlg, 1);
VpStd = nan(nAlg, 1);

HMean = nan(nAlg, 1);
HStd = nan(nAlg, 1);

for iAlg = 1:nAlg

    BestFitness(iAlg) = ...
        min_omitnan(FinalFitness_all(:, iAlg));

    MeanFitness(iAlg) = ...
        mean_omitnan(FinalFitness_all(:, iAlg), 1);

    MedianFitness(iAlg) = ...
        median_omitnan(FinalFitness_all(:, iAlg));

    StdFitness(iAlg) = ...
        std_omitnan(FinalFitness_all(:, iAlg));

    WorstFitness(iAlg) = ...
        max_omitnan(FinalFitness_all(:, iAlg));

    VsMean(iAlg) = ...
        mean_omitnan(VsRMSE_all(:, iAlg), 1);

    VsStd(iAlg) = ...
        std_omitnan(VsRMSE_all(:, iAlg));

    VpMean(iAlg) = ...
        mean_omitnan(VpRMSE_all(:, iAlg), 1);

    VpStd(iAlg) = ...
        std_omitnan(VpRMSE_all(:, iAlg));

    HMean(iAlg) = ...
        mean_omitnan(HRMSE_all(:, iAlg), 1);

    HStd(iAlg) = ...
        std_omitnan(HRMSE_all(:, iAlg));
end

summaryTable = table( ...
    algNames(:), ...
    BestFitness, ...
    MeanFitness, ...
    MedianFitness, ...
    StdFitness, ...
    WorstFitness, ...
    VsMean, ...
    VsStd, ...
    VpMean, ...
    VpStd, ...
    HMean, ...
    HStd, ...
    'VariableNames', { ...
        'Method', ...
        'BestFitness', ...
        'MeanFitness', ...
        'MedianFitness', ...
        'StdFitness', ...
        'WorstFitness', ...
        'VsRMSE_Mean', ...
        'VsRMSE_Std', ...
        'VpRMSE_Mean', ...
        'VpRMSE_Std', ...
        'HRMSE_Mean', ...
        'HRMSE_Std'});

figure( ...
    'Name', 'Fitness convergence comparison', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [100, 100, 900, 560]);

hold on;

for iAlg = 1:nAlg

    plot( ...
        0:Max_it-1, ...
        Convergence_mean(iAlg, :), ...
        'LineWidth', 1.6);
end

hold off;

xlabel( ...
    'Iteration', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

ylabel( ...
    'Mean best fitness', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    algNames, ...
    'Location', 'northeast', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10);

title( ...
    'Convergence comparison of inversion algorithms', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12, ...
    'LineWidth', 1.0);

exportgraphics( ...
    gcf, ...
    'Fig_algorithm_convergence.png', ...
    'Resolution', 600);

figure( ...
    'Name', 'Dispersion-curve comparison', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [150, 120, 820, 540]);

plot( ...
    freq, ...
    pv_true, ...
    'k-', ...
    'LineWidth', 2.2);

hold on;

for iAlg = 1:nAlg

    plot( ...
        freq, ...
        Dispersion_matrix(:, iAlg), ...
        'LineWidth', 1.5);
end

hold off;

xlabel( ...
    'Frequency (Hz)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

ylabel( ...
    'Phase velocity (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    [{'Theoretical'}, algNames], ...
    'Location', 'best', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10);

title( ...
    'Comparison of inverted dispersion curves', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12, ...
    'LineWidth', 1.0);

exportgraphics( ...
    gcf, ...
    'Fig_dispersion_comparison.png', ...
    'Resolution', 600);

paramMean = [VsMean, VpMean, HMean];
paramStd = [VsStd, VpStd, HStd];

figure( ...
    'Name', 'Parameter recovery RMSE comparison', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [200, 150, 1050, 560]);

bar(paramMean);

hold on;

nGroups = size(paramMean, 1);
nBars = size(paramMean, 2);

groupWidth = min(0.80, nBars / (nBars + 1.5));

for iBar = 1:nBars

    xPos = ...
        (1:nGroups) ...
        - groupWidth / 2 ...
        + (2 * iBar - 1) * groupWidth / (2 * nBars);

    errorbar( ...
        xPos, ...
        paramMean(:, iBar), ...
        paramStd(:, iBar), ...
        'k.', ...
        'LineWidth', 1.0, ...
        'CapSize', 7);
end

hold off;

set( ...
    gca, ...
    'XTick', 1:nAlg, ...
    'XTickLabel', algNames, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 1.0);

ylabel( ...
    'Parameter RMSE', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    {'Vs RMSE', 'Vp RMSE', 'H RMSE'}, ...
    'Location', 'northeast', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

title( ...
    'Parameter recovery RMSE comparison', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

exportgraphics( ...
    gcf, ...
    'Fig_parameter_RMSE_bar.png', ...
    'Resolution', 600);

figure( ...
    'Name', 'Final fitness boxplot', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [240, 180, 1050, 540]);

boxplot( ...
    FinalFitness_all, ...
    'Labels', algNames);

ylabel( ...
    'Final best fitness', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

title( ...
    'Final fitness distribution', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 1.0);

exportgraphics( ...
    gcf, ...
    'Fig_final_fitness_boxplot.png', ...
    'Resolution', 600);

figure( ...
    'Name', 'Vs RMSE boxplot', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [260, 200, 1050, 540]);

boxplot( ...
    VsRMSE_all, ...
    'Labels', algNames);

ylabel( ...
    'Vs RMSE (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

title( ...
    'Vs recovery RMSE distribution', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 1.0);

exportgraphics( ...
    gcf, ...
    'Fig_Vs_RMSE_boxplot.png', ...
    'Resolution', 600);

figure( ...
    'Name', 'Vp RMSE boxplot', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [280, 220, 1050, 540]);

boxplot( ...
    VpRMSE_all, ...
    'Labels', algNames);

ylabel( ...
    'Vp RMSE (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

title( ...
    'Vp recovery RMSE distribution', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 1.0);

exportgraphics( ...
    gcf, ...
    'Fig_Vp_RMSE_boxplot.png', ...
    'Resolution', 600_Vp_RMSE_boxplot.png', ...
    'Resolution', 600);

figure( ...
    'Name', 'H RMSE boxplot', ...
    'NumberTitle', 'off', ...
    'Color', 'w', ...
    'Position', [300, 240, 1050, 540]);

boxplot( ...
    HRMSE_all, ...
    'Labels', algNames);

ylabel( ...
    'H RMSE (m)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

title( ...
    'Layer-thickness recovery RMSE distribution', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 15, ...
    'FontWeight', 'normal');

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 1.0);

exportgraphics( ...
    gcf, ...
    'Fig_H_RMSE_boxplot.png', ...
    'Resolution', 600);

Results = struct();

for iAlg = 1:nAlg

    key = matlab.lang.makeValidName(algNames{iAlg});

    Results.(key).PositionAll = ...
        Position_all(:, :, iAlg);

    Results.(key).PositionMean = ...
        Position_mean(iAlg, :);

    Results.(key).FinalFitness = ...
        FinalFitness_all(:, iAlg);

    Results.(key).ConvergenceAll = ...
        Convergence_all(:, :, iAlg);

    Results.(key).ConvergenceMean = ...
        Convergence_mean(iAlg, :);

    Results.(key).VsRMSE = ...
        VsRMSE_all(:, iAlg);

    Results.(key).VpRMSE = ...
        VpRMSE_all(:, iAlg);

    Results.(key).HRMSE = ...
        HRMSE_all(:, iAlg);

    Results.(key).Dispersion = ...
        Dispersion_matrix(:, iAlg);
end

Convergence_means = struct();

for iAlg = 1:nAlg

    key = matlab.lang.makeValidName(algNames{iAlg});

    Convergence_means.(key) = ...
        Convergence_mean(iAlg, :);
end

Dispersion_curves = struct();

Dispersion_curves.freq = freq;
Dispersion_curves.theoretical = pv_true;

for iAlg = 1:nAlg

    key = matlab.lang.makeValidName(algNames{iAlg});

    Dispersion_curves.(key) = ...
        Dispersion_matrix(:, iAlg);
end

save_filename = sprintf( ...
    'Inversion_Results_Nrun%d_Npop%d_Maxit%d.mat', ...
    Nrun, ...
    Npop, ...
    Max_it);

save( ...
    save_filename, ...
    'Results', ...
    'Convergence_means', ...
    'Dispersion_curves', ...
    'summaryTable', ...
    'algNames', ...
    'VS_true', ...
    'VP_true', ...
    'H_true', ...
    'den', ...
    'freq', ...
    'pv_true', ...
    'lb', ...
    'ub', ...
    'Position_all', ...
    'Convergence_all', ...
    'FinalFitness_all', ...
    'VsRMSE_all', ...
    'VpRMSE_all', ...
    'HRMSE_all', ...
    '-v7.3');

end


function curveOut = fit_curve_length(curveIn, targetLen)

curveIn = curveIn(:).';

curveOut = nan(1, targetLen);

if isempty(curveIn)
    return;
end

n = min(numel(curveIn), targetLen);

curveOut(1:n) = curveIn(1:n);

if n < targetLen
    curveOut(n + 1:end) = curveIn(n);
end

end


function f = safe_objective(x, fitness_func)

if isempty(x) || any(~isfinite(x))
    f = NaN;
    return;
end

try

    temp = fitness_func(x);

    if isempty(temp) || ...
            ~isscalar(temp) || ...
            ~isreal(temp) || ...
            ~isfinite(temp)

        f = NaN;

    else

        f = double(temp);
    end

catch

    f = NaN;
end

end


function rmseVal = parameter_rmse(paramMat, trueParam)

trueParam = trueParam(:).';

nRun = size(paramMat, 1);

rmseVal = nan(nRun, 1);

for i = 1:nRun

    x = paramMat(i, :);

    if any(~isfinite(x))

        rmseVal(i) = NaN;

    else

        rmseVal(i) = ...
            sqrt(mean((x - trueParam) .^ 2));
    end
end

end


function pv = safe_phase_curve(freq, x, den)

freq = freq(:);

pv = nan(size(freq));

if isempty(x) || any(~isfinite(x))
    return;
end

try

    temp = calcbase( ...
        freq, ...
        x(1:4), ...
        x(5:7), ...
        x(8:11), ...
        den);

    temp = temp(:);

    n = min(numel(temp), numel(freq));

    pv(1:n) = temp(1:n);

catch

    pv(:) = NaN;
end

end


function out = mean_omitnan(x, dim)

if nargin < 2
    dim = 1;
end

mask = isfinite(x);

x2 = x;
x2(~mask) = 0;

count = sum(mask, dim);

out = sum(x2, dim) ./ count;

out(count == 0) = NaN;

end


function out = std_omitnan(x)

x = x(:);
x = x(isfinite(x));

if numel(x) <= 1
    out = NaN;
else
    out = std(x, 0);
end

end


function out = min_omitnan(x)

x = x(:);
x = x(isfinite(x));

if isempty(x)
    out = NaN;
else
    out = min(x);
end

end


function out = max_omitnan(x)

x = x(:);
x = x(isfinite(x));

if isempty(x)
    out = NaN;
else
    out = max(x);
end

end


function out = median_omitnan(x)

x = x(:);
x = x(isfinite(x));

if isempty(x)
    out = NaN;
else
    out = median(x);
end

end


function SABO_all = infer_sabo_positions( ...
    out1, out3, Nrun, nD)

SABO_all = nan(Nrun, nD);

candidates = {out1, out3};

for k = 1:numel(candidates)

    temp = candidates{k};

    if isempty(temp) || ~isnumeric(temp)
        continue;
    end

    sz = size(temp);

    if isequal(sz, [Nrun, nD])

        SABO_all = temp;
        return;

    elseif isequal(sz, [nD, Nrun])

        SABO_all = temp.';
        return;

    elseif isvector(temp) && numel(temp) == nD

        SABO_all = repmat(temp(:).', Nrun, 1);
        return;
    end
end

warning( ...
    ['SABO parameter results could not be identified as an ', ...
     'Nrun-by-nD matrix. SABO parameter RMSE values will be NaN.']);

end