clear;
clc;
close all;

runMode = 'formal';

saveIterationData = true;
savePopulationHistory = true;
useParallel = true;

switch lower(runMode)

    case 'debug'

        Npop = 50;
        Max_it = 30;
        Nrun = 2;

    case 'formal'

        Npop = 200;
        Max_it = 200;
        Nrun = 20;

    otherwise

        error('runMode must be either ''debug'' or ''formal''.');
end

global n_mode
n_mode = 1;

fmin = 2;
df = 0.5;
fmax = 80;

freq = fmin:df:fmax;

VS_true = [];
H_true = [];
VP_true = [];
den = [];

pv_all = calcmulti( ...
    freq, ...
    VS_true, ...
    H_true, ...
    VP_true, ...
    den);

pv_obs = pv_all(:, 1);
pv_obs = pv_obs(:);

fitness_func = @(x) compute_fitness_base( ...
    x, ...
    freq, ...
    pv_obs, ...
    den);

lb = [];

ub = [];

dim = numel(lb);

if dim ~= 11
    error('The parameter vector must contain 11 dimensions.');
end

if numel(ub) ~= dim
    error('lb and ub must have the same dimensions.');
end

if any(ub < lb)
    error('Each dimension must satisfy ub >= lb.');
end

algNames = { ...
    'B0 Standard HHO', ...
    'B1 Sobol-HHO', ...
    'B2 Sobol + Adaptive E/J', ...
    'B3 B2 + Elite Guidance', ...
    'B4 B3 + Stagnation Repair'};

nAlg = numel(algNames);

cfg_B0 = struct( ...
    'useAdaptiveEJ', false, ...
    'useEliteGuidance', false, ...
    'useStagnationRepair', false, ...
    'saveIterationData', saveIterationData, ...
    'savePopulationHistory', savePopulationHistory, ...
    'verbose', false, ...
    'algorithmName', 'B0 Standard HHO');

cfg_B1 = struct( ...
    'useAdaptiveEJ', false, ...
    'useEliteGuidance', false, ...
    'useStagnationRepair', false, ...
    'saveIterationData', saveIterationData, ...
    'savePopulationHistory', savePopulationHistory, ...
    'verbose', false, ...
    'algorithmName', 'B1 Sobol-HHO');

cfg_B2 = struct( ...
    'useAdaptiveEJ', true, ...
    'useEliteGuidance', false, ...
    'useStagnationRepair', false, ...
    'saveIterationData', saveIterationData, ...
    'savePopulationHistory', savePopulationHistory, ...
    'verbose', false, ...
    'algorithmName', 'B2 DA-HHO');

cfg_B3 = struct( ...
    'useAdaptiveEJ', true, ...
    'useEliteGuidance', true, ...
    'useStagnationRepair', false, ...
    'saveIterationData', saveIterationData, ...
    'savePopulationHistory', savePopulationHistory, ...
    'verbose', false, ...
    'algorithmName', 'B3 DAE-HHO');

cfg_B4 = struct( ...
    'useAdaptiveEJ', true, ...
    'useEliteGuidance', true, ...
    'useStagnationRepair', true, ...
    'saveIterationData', saveIterationData, ...
    'savePopulationHistory', savePopulationHistory, ...
    'verbose', false, ...
    'algorithmName', 'B4 DAEG-HHO');

f_all = nan(Nrun, nAlg);
x_all = nan(Nrun, dim, nAlg);
hist_all = nan(Nrun, Max_it, nAlg);
time_all = nan(Nrun, nAlg);
nfe_all = nan(Nrun, nAlg);
diag_all = cell(Nrun, nAlg);

if useParallel

    try

        if ~license('test', 'Distrib_Computing_Toolbox')

            useParallel = false;

        elseif isempty(gcp('nocreate'))

            parpool('local');
        end

    catch

        useParallel = false;
    end
end

for irun = 1:Nrun

    initialSeed = 1000 + irun;
    searchSeed = 10000 + irun;

    rng(initialSeed, 'twister');

    tStart = tic;

    [f_B0, x_B0, hist_B0, diag_B0] = ...
        HHO_Core_Rayleigh( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_func, ...
        useParallel, ...
        searchSeed, ...
        'random', ...
        cfg_B0);

    time_B0 = toc(tStart);

    f_all(irun, 1) = f_B0;
    x_all(irun, :, 1) = x_B0;
    hist_all(irun, :, 1) = hist_B0;
    time_all(irun, 1) = time_B0;
    nfe_all(irun, 1) = diag_B0.totalEvaluations;
    diag_all{irun, 1} = diag_B0;

    rng(initialSeed, 'twister');

    tStart = tic;

    [f_B1, x_B1, hist_B1, diag_B1] = ...
        HHO_Core_Rayleigh( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_func, ...
        useParallel, ...
        searchSeed, ...
        'sobol', ...
        cfg_B1);

    time_B1 = toc(tStart);

    f_all(irun, 2) = f_B1;
    x_all(irun, :, 2) = x_B1;
    hist_all(irun, :, 2) = hist_B1;
    time_all(irun, 2) = time_B1;
    nfe_all(irun, 2) = diag_B1.totalEvaluations;
    diag_all{irun, 2} = diag_B1;

    rng(initialSeed, 'twister');

    tStart = tic;

    [f_B2, x_B2, hist_B2, diag_B2] = ...
        HHO_Core_Rayleigh( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_func, ...
        useParallel, ...
        searchSeed, ...
        'sobol', ...
        cfg_B2);

    time_B2 = toc(tStart);

    f_all(irun, 3) = f_B2;
    x_all(irun, :, 3) = x_B2;
    hist_all(irun, :, 3) = hist_B2;
    time_all(irun, 3) = time_B2;
    nfe_all(irun, 3) = diag_B2.totalEvaluations;
    diag_all{irun, 3} = diag_B2;

    rng(initialSeed, 'twister');

    tStart = tic;

    [f_B3, x_B3, hist_B3, diag_B3] = ...
        HHO_Core_Rayleigh( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_func, ...
        useParallel, ...
        searchSeed, ...
        'sobol', ...
        cfg_B3);

    time_B3 = toc(tStart);

    f_all(irun, 4) = f_B3;
    x_all(irun, :, 4) = x_B3;
    hist_all(irun, :, 4) = hist_B3;
    time_all(irun, 4) = time_B3;
    nfe_all(irun, 4) = diag_B3.totalEvaluations;
    diag_all{irun, 4} = diag_B3;

    rng(initialSeed, 'twister');

    tStart = tic;

    [f_B4, x_B4, hist_B4, diag_B4] = ...
        HHO_Core_Rayleigh( ...
        Npop, ...
        Max_it, ...
        lb, ...
        ub, ...
        fitness_func, ...
        useParallel, ...
        searchSeed, ...
        'sobol', ...
        cfg_B4);

    time_B4 = toc(tStart);

    f_all(irun, 5) = f_B4;
    x_all(irun, :, 5) = x_B4;
    hist_all(irun, :, 5) = hist_B4;
    time_all(irun, 5) = time_B4;
    nfe_all(irun, 5) = diag_B4.totalEvaluations;
    diag_all{irun, 5} = diag_B4;
end

vs_rmse = nan(Nrun, nAlg);
vp_rmse = nan(Nrun, nAlg);
h_rmse = nan(Nrun, nAlg);

VS_true_matrix = repmat(VS_true, Nrun, 1);
VP_true_matrix = repmat(VP_true, Nrun, 1);
H_true_matrix = repmat(H_true, Nrun, 1);

for iAlg = 1:nAlg

    X_result = x_all(:, :, iAlg);

    Vs_result = X_result(:, 1:4);
    H_result = X_result(:, 5:7);
    Vp_result = X_result(:, 8:11);

    vs_rmse(:, iAlg) = sqrt(mean( ...
        (Vs_result - VS_true_matrix) .^ 2, ...
        2));

    vp_rmse(:, iAlg) = sqrt(mean( ...
        (Vp_result - VP_true_matrix) .^ 2, ...
        2));

    h_rmse(:, iAlg) = sqrt(mean( ...
        (H_result - H_true_matrix) .^ 2, ...
        2));
end

summaryTable = table( ...
    algNames.', ...
    min(f_all, [], 1).', ...
    mean(f_all, 1).', ...
    median(f_all, 1).', ...
    std(f_all, 0, 1).', ...
    max(f_all, [], 1).', ...
    mean(time_all, 1).', ...
    std(time_all, 0, 1).', ...
    mean(nfe_all, 1).', ...
    std(nfe_all, 0, 1).', ...
    mean(vs_rmse, 1).', ...
    std(vs_rmse, 0, 1).', ...
    mean(vp_rmse, 1).', ...
    std(vp_rmse, 0, 1).', ...
    mean(h_rmse, 1).', ...
    std(h_rmse, 0, 1).', ...
    'VariableNames', { ...
        'Method', ...
        'BestFitness', ...
        'MeanFitness', ...
        'MedianFitness', ...
        'StdFitness', ...
        'WorstFitness', ...
        'MeanTime_s', ...
        'StdTime_s', ...
        'MeanNFE', ...
        'StdNFE', ...
        'VsRMSE_Mean', ...
        'VsRMSE_Std', ...
        'VpRMSE_Mean', ...
        'VpRMSE_Std', ...
        'HRMSE_Mean', ...
        'HRMSE_Std'});

pairNames = { ...
    'B0 Standard vs B1 Sobol', ...
    'B1 Sobol vs B2 Adaptive E/J', ...
    'B2 Adaptive E/J vs B3 Elite Guidance', ...
    'B3 Elite Guidance vs B4 Stagnation Repair'};

pValues = nan(4, 1);

pValues(1) = safe_signrank(f_all(:, 1), f_all(:, 2));
pValues(2) = safe_signrank(f_all(:, 2), f_all(:, 3));
pValues(3) = safe_signrank(f_all(:, 3), f_all(:, 4));
pValues(4) = safe_signrank(f_all(:, 4), f_all(:, 5));

pTable = table( ...
    pairNames.', ...
    pValues, ...
    pValues < 0.05, ...
    'VariableNames', { ...
        'Comparison', ...
        'pValue', ...
        'Significant_0_05'});

meanHist = squeeze(mean(hist_all, 1));

figure( ...
    'Color', 'w', ...
    'Position', [140, 100, 820, 520]);

semilogy( ...
    1:Max_it, ...
    meanHist, ...
    'LineWidth', 1.5);

xlabel( ...
    'Iteration', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

ylabel( ...
    'Mean best fitness (RMSE)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    algNames, ...
    'Location', 'northeast', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10);

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

figure( ...
    'Color', 'w', ...
    'Position', [170, 130, 900, 520]);

boxplot( ...
    f_all, ...
    'Labels', algNames);

ylabel( ...
    'Final best fitness (RMSE)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

paramMean = [ ...
    mean(vs_rmse, 1).', ...
    mean(vp_rmse, 1).', ...
    mean(h_rmse, 1).'];

paramStd = [ ...
    std(vs_rmse, 0, 1).', ...
    std(vp_rmse, 0, 1).', ...
    std(h_rmse, 0, 1).'];

figure( ...
    'Color', 'w', ...
    'Position', [200, 160, 920, 540]);

bar(paramMean);

hold on;

nGroups = size(paramMean, 1);
nBars = size(paramMean, 2);

groupWidth = min( ...
    0.80, ...
    nBars / (nBars + 1.5));

for iBar = 1:nBars

    xPos = ...
        (1:nGroups) ...
        - groupWidth / 2 ...
        + (2 * iBar - 1) * groupWidth / (2 * nBars);

    errorbar( ...
        xPos, ...
        paramMean(:, iBar), ...
        paramStd(:, iBar), ...
        'k.', ...
        'LineWidth', 1.0);
end

hold off;

set( ...
    gca, ...
    'XTick', 1:nAlg, ...
    'XTickLabel', algNames, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10);

ylabel( ...
    'Parameter recovery RMSE', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    {'Vs RMSE', 'Vp RMSE', 'H RMSE'}, ...
    'Location', 'northeast', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

grid on;
box on;

idx_B0 = median_run_index(f_all(:, 1));
idx_B4 = median_run_index(f_all(:, 5));

x_B0_rep = squeeze(x_all(idx_B0, :, 1));
x_B4_rep = squeeze(x_all(idx_B4, :, 5));

pv_B0 = calcmulti( ...
    freq, ...
    x_B0_rep(1:4), ...
    x_B0_rep(5:7), ...
    x_B0_rep(8:11), ...
    den);

pv_B0 = pv_B0(:, 1);

pv_B4 = calcmulti( ...
    freq, ...
    x_B4_rep(1:4), ...
    x_B4_rep(5:7), ...
    x_B4_rep(8:11), ...
    den);

pv_B4 = pv_B4(:, 1);

figure( ...
    'Color', 'w', ...
    'Position', [240, 190, 720, 500]);

plot( ...
    freq, ...
    pv_obs, ...
    'k-', ...
    'LineWidth', 1.8);

hold on;

plot( ...
    freq, ...
    pv_B0, ...
    '--', ...
    'LineWidth', 1.6);

plot( ...
    freq, ...
    pv_B4, ...
    '-.', ...
    'LineWidth', 1.6);

hold off;

xlabel( ...
    'Frequency (Hz)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

ylabel( ...
    'Phase velocity (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    {'True', 'B0 Standard HHO', 'B4 DAEG-HHO'}, ...
    'Location', 'best', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

zMax = sum(H_true) + 2;

[Vs_true_plot, z_true_plot] = ...
    make_vs_step_profile( ...
    VS_true, ...
    H_true, ...
    zMax);

[Vs_B0_plot, z_B0_plot] = ...
    make_vs_step_profile( ...
    x_B0_rep(1:4), ...
    x_B0_rep(5:7), ...
    zMax);

[Vs_B4_plot, z_B4_plot] = ...
    make_vs_step_profile( ...
    x_B4_rep(1:4), ...
    x_B4_rep(5:7), ...
    zMax);

figure( ...
    'Color', 'w', ...
    'Position', [280, 220, 620, 540]);

plot( ...
    Vs_true_plot, ...
    z_true_plot, ...
    'k-', ...
    'LineWidth', 2.0);

hold on;

plot( ...
    Vs_B0_plot, ...
    z_B0_plot, ...
    '--', ...
    'LineWidth', 1.6);

plot( ...
    Vs_B4_plot, ...
    z_B4_plot, ...
    '-.', ...
    'LineWidth', 1.6);

hold off;

set(gca, 'YDir', 'reverse');

xlabel( ...
    'Vs (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

ylabel( ...
    'Depth (m)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

legend( ...
    {'True', 'B0 Standard HHO', 'B4 DAEG-HHO'}, ...
    'Location', 'best', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

grid on;
box on;

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

parameterNames = { ...
    'Vs1', ...
    'Vs2', ...
    'Vs3', ...
    'Vs4', ...
    'H1', ...
    'H2', ...
    'H3', ...
    'Vp1', ...
    'Vp2', ...
    'Vp3', ...
    'Vp4'};

B0 = collect_algorithm_data( ...
    algNames{1}, ...
    f_all(:, 1), ...
    x_all(:, :, 1), ...
    hist_all(:, :, 1), ...
    time_all(:, 1), ...
    nfe_all(:, 1), ...
    vs_rmse(:, 1), ...
    vp_rmse(:, 1), ...
    h_rmse(:, 1), ...
    diag_all(:, 1), ...
    parameterNames);

B1 = collect_algorithm_data( ...
    algNames{2}, ...
    f_all(:, 2), ...
    x_all(:, :, 2), ...
    hist_all(:, :, 2), ...
    time_all(:, 2), ...
    nfe_all(:, 2), ...
    vs_rmse(:, 2), ...
    vp_rmse(:, 2), ...
    h_rmse(:, 2), ...
    diag_all(:, 2), ...
    parameterNames);

B2 = collect_algorithm_data( ...
    algNames{3}, ...
    f_all(:, 3), ...
    x_all(:, :, 3), ...
    hist_all(:, :, 3), ...
    time_all(:, 3), ...
    nfe_all(:, 3), ...
    vs_rmse(:, 3), ...
    vp_rmse(:, 3), ...
    h_rmse(:, 3), ...
    diag_all(:, 3), ...
    parameterNames);

B3 = collect_algorithm_data( ...
    algNames{4}, ...
    f_all(:, 4), ...
    x_all(:, :, 4), ...
    hist_all(:, :, 4), ...
    time_all(:, 4), ...
    nfe_all(:, 4), ...
    vs_rmse(:, 4), ...
    vp_rmse(:, 4), ...
    h_rmse(:, 4), ...
    diag_all(:, 4), ...
    parameterNames);

B4 = collect_algorithm_data( ...
    algNames{5}, ...
    f_all(:, 5), ...
    x_all(:, :, 5), ...
    hist_all(:, :, 5), ...
    time_all(:, 5), ...
    nfe_all(:, 5), ...
    vs_rmse(:, 5), ...
    vp_rmse(:, 5), ...
    h_rmse(:, 5), ...
    diag_all(:, 5), ...
    parameterNames);

allResults = struct();

allResults.settings = struct( ...
    'runMode', runMode, ...
    'Npop', Npop, ...
    'MaxIteration', Max_it, ...
    'Nrun', Nrun, ...
    'Frequency', freq, ...
    'VS_true', VS_true, ...
    'VP_true', VP_true, ...
    'H_true', H_true, ...
    'Density', den, ...
    'lb', lb, ...
    'ub', ub, ...
    'parameterNames', {parameterNames});

allResults.B0 = B0;
allResults.B1 = B1;
allResults.B2 = B2;
allResults.B3 = B3;
allResults.B4 = B4;

iterationData_all = diag_all;

allResults.iterationData_all = iterationData_all;
allResults.summaryTable = summaryTable;
allResults.pTable = pTable;

resultFile = sprintf( ...
    'HHO_stepwise_ablation_%s.mat', ...
    lower(runMode));

save( ...
    resultFile, ...
    'runMode', ...
    'Npop', ...
    'Max_it', ...
    'Nrun', ...
    'saveIterationData', ...
    'savePopulationHistory', ...
    'freq', ...
    'pv_obs', ...
    'VS_true', ...
    'VP_true', ...
    'H_true', ...
    'den', ...
    'lb', ...
    'ub', ...
    'algNames', ...
    'f_all', ...
    'x_all', ...
    'hist_all', ...
    'time_all', ...
    'nfe_all', ...
    'vs_rmse', ...
    'vp_rmse', ...
    'h_rmse', ...
    'summaryTable', ...
    'pTable', ...
    'diag_all', ...
    'iterationData_all', ...
    'B0', ...
    'B1', ...
    'B2', ...
    'B3', ...
    'B4', ...
    'allResults', ...
    '-v7.3');


function p = safe_signrank(x, y)

x = x(:);
y = y(:);

valid = isfinite(x) & isfinite(y);

x = x(valid);
y = y(valid);

if numel(x) < 5
    p = NaN;
    return;
end

try
    p = signrank(x, y);
catch
    p = NaN;
end

end


function idx = median_run_index(values)

values = values(:);

validIndex = find(isfinite(values));

if isempty(validIndex)
    error('No finite run result is available.');
end

validValues = values(validIndex);

[~, order] = sort(validValues, 'ascend');

middleIndex = ceil(numel(validValues) / 2);

idx = validIndex(order(middleIndex));

end


function [vsPlot, zPlot] = ...
    make_vs_step_profile(vs, h, zMax)

vs = vs(:).';
h = h(:).';

nLayer = numel(vs);

if numel(h) ~= nLayer - 1
    error('The number of Vs layers must exceed the number of thickness parameters by one.');
end

if zMax <= sum(h)
    zMax = sum(h) + eps;
end

zEdge = [0, cumsum(h), zMax];

vsPlot = zeros(1, 2 * nLayer);
zPlot = zeros(1, 2 * nLayer);

for k = 1:nLayer

    vsPlot(2 * k - 1) = vs(k);
    vsPlot(2 * k) = vs(k);

    zPlot(2 * k - 1) = zEdge(k);
    zPlot(2 * k) = zEdge(k + 1);
end

end


function result = collect_algorithm_data( ...
    methodName, ...
    finalFitness, ...
    bestParameters, ...
    convergenceHistory, ...
    runtime_s, ...
    nfe, ...
    vsRMSE, ...
    vpRMSE, ...
    hRMSE, ...
    diagnostics, ...
    parameterNames)

nRun = numel(finalFitness);

result = struct();

result.name = methodName;
result.runIndex = (1:nRun).';
result.finalFitness = finalFitness(:);
result.bestParameters = bestParameters;
result.convergenceHistory = convergenceHistory;
result.runtime_s = runtime_s(:);
result.NFE = nfe(:);
result.VsRMSE = vsRMSE(:);
result.VpRMSE = vpRMSE(:);
result.HRMSE = hRMSE(:);
result.iterationData = diagnostics;
result.diagnostics = diagnostics;

result.populationHistory = cell(nRun, 1);
result.fitnessHistory = cell(nRun, 1);
result.bestPositionHistory = cell(nRun, 1);
result.currentBestPositionHistory = cell(nRun, 1);
result.meanPositionHistory = cell(nRun, 1);

for irun = 1:nRun

    currentDiag = diagnostics{irun};

    if isempty(currentDiag) || ~isstruct(currentDiag)
        continue;
    end

    if isfield(currentDiag, 'populationHistory')

        result.populationHistory{irun} = ...
            currentDiag.populationHistory;
    end

    if isfield(currentDiag, 'fitnessHistory')

        result.fitnessHistory{irun} = ...
            currentDiag.fitnessHistory;
    end

    if isfield(currentDiag, 'bestPositionHistory')

        result.bestPositionHistory{irun} = ...
            currentDiag.bestPositionHistory;
    end

    if isfield(currentDiag, 'currentBestPositionHistory')

        result.currentBestPositionHistory{irun} = ...
            currentDiag.currentBestPositionHistory;
    end

    if isfield(currentDiag, 'meanPositionHistory')

        result.meanPositionHistory{irun} = ...
            currentDiag.meanPositionHistory;
    end
end

result.parameterNames = parameterNames;

result.parameterTable = array2table( ...
    bestParameters, ...
    'VariableNames', parameterNames);

result.parameterTable.Run = (1:nRun).';

result.parameterTable = movevars( ...
    result.parameterTable, ...
    'Run', ...
    'Before', ...
    1);

result.runTable = table( ...
    (1:nRun).', ...
    finalFitness(:), ...
    runtime_s(:), ...
    nfe(:), ...
    vsRMSE(:), ...
    vpRMSE(:), ...
    hRMSE(:), ...
    'VariableNames', { ...
        'Run', ...
        'FinalFitness', ...
        'Time_s', ...
        'NFE', ...
        'VsRMSE', ...
        'VpRMSE', ...
        'HRMSE'});

result.statistics = struct();

result.statistics.BestFitness = ...
    min(finalFitness, [], 'omitnan');

result.statistics.MeanFitness = ...
    mean(finalFitness, 'omitnan');

result.statistics.MedianFitness = ...
    median(finalFitness, 'omitnan');

result.statistics.StdFitness = ...
    std(finalFitness, 0, 'omitnan');

result.statistics.WorstFitness = ...
    max(finalFitness, [], 'omitnan');

result.statistics.MeanTime_s = ...
    mean(runtime_s, 'omitnan');

result.statistics.StdTime_s = ...
    std(runtime_s, 0, 'omitnan');

result.statistics.MeanNFE = ...
    mean(nfe, 'omitnan');

result.statistics.StdNFE = ...
    std(nfe, 0, 'omitnan');

result.statistics.VsRMSE_Mean = ...
    mean(vsRMSE, 'omitnan');

result.statistics.VsRMSE_Std = ...
    std(vsRMSE, 0, 'omitnan');

result.statistics.VpRMSE_Mean = ...
    mean(vpRMSE, 'omitnan');

result.statistics.VpRMSE_Std = ...
    std(vpRMSE, 0, 'omitnan');

result.statistics.HRMSE_Mean = ...
    mean(hRMSE, 'omitnan');

result.statistics.HRMSE_Std = ...
    std(hRMSE, 0, 'omitnan');

end