clear;
close all;
clc;

fmin = ;
df = ;
fmax = ;

freq = fmin:df:fmax;
flen = length(freq);

VS_true = [];
VP_true = [];
H_true = [];
den = [];

global n_mode
n_mode = 1;

pv = calcmulti(freq, VS_true, H_true, VP_true, den);
pv = pv(:, 1);

Npop = 200;
Max_it = 200;
nD = 14;

lb = [];
ub = [];

fitness_func = @(x) compute_fitness_base(x, freq, pv, den);

Nrun = 20;

x_all_dlh = zeros(Nrun, nD);
f_all_dlh = zeros(Nrun, 1);
hist_all_dlh = nan(Nrun, Max_it);

for irun = 1:Nrun

    [f_best, x_best, histout] = HHO_Sobol_DAEG_Rayleigh( ...
        Npop, Max_it, lb, ub, fitness_func);

    x_all_dlh(irun, :) = x_best;
    f_all_dlh(irun) = f_best;
    hist_all_dlh(irun, :) = histout(:).';
end

x_mean_dlh = mean(x_all_dlh, 1);

[~, idx_best] = min(f_all_dlh);

x_best_dlh = x_all_dlh(idx_best, :);

pv_true = pv;

vs_mean = x_mean_dlh(1:5);
h_mean = x_mean_dlh(6:9);
h_best = x_best_dlh(6:9);
vp_mean = x_mean_dlh(10:14);

pv_mean = calcmulti(freq, vs_mean, h_mean, vp_mean, den);
pv_mean = pv_mean(:, 1);

figure('Color', 'w');

hold on;
box on;

plot( ...
    freq, ...
    pv_true, ...
    'k-o', ...
    'LineWidth', 1, ...
    'MarkerSize', 2.5, ...
    'MarkerFaceColor', 'k');

plot( ...
    freq, ...
    pv_mean, ...
    'r', ...
    'LineWidth', 2);

xlabel( ...
    'Frequency (Hz)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

ylabel( ...
    'Phase Velocity (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

legend( ...
    'Target dispersion curve', ...
    'Mean inverted dispersion curve', ...
    'Location', 'best', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 14);

figure(3);

set(gcf, 'Color', 'w');

X_l = sum(H_true) + 5;

thk_m = sum(h_mean) + 6.5;
thk_b = sum(h_best) + 5;

thk_ub = sum(ub(5:7)) + 0.5;
thk_lb = sum(lb(5:7)) + 9.5;

thk_l = [ ...
    X_l, ...
    sum(H_true), ...
    sum(H_true), ...
    sum(H_true(1) + H_true(2)), ...
    sum(H_true(1) + H_true(2)), ...
    H_true(1), ...
    H_true(1), ...
    0];

thk_b = [ ...
    thk_b, ...
    sum(x_best_dlh(5:7)), ...
    sum(x_best_dlh(5:7)), ...
    sum(x_best_dlh(5:6)), ...
    sum(x_best_dlh(5:6)), ...
    x_best_dlh(5), ...
    x_best_dlh(5), ...
    0];

thk_m = [ ...
    thk_m, ...
    sum(x_mean_dlh(5:7)), ...
    sum(x_mean_dlh(5:7)), ...
    sum(x_mean_dlh(5:6)), ...
    sum(x_mean_dlh(5:6)), ...
    x_mean_dlh(5), ...
    x_mean_dlh(5), ...
    0];

thk_ub = [ ...
    thk_ub, ...
    sum(ub(5:7)), ...
    sum(ub(5:7)), ...
    sum(ub(5:6)), ...
    sum(ub(5:6)), ...
    ub(5), ...
    ub(5), ...
    0];

thk_lb = [ ...
    thk_lb, ...
    sum(lb(5:7)), ...
    sum(lb(5:7)), ...
    sum(lb(5:6)), ...
    sum(lb(5:6)), ...
    lb(5), ...
    lb(5), ...
    0];

vs_l = [ ...
    VS_true(4), ...
    VS_true(4), ...
    VS_true(3), ...
    VS_true(3), ...
    VS_true(2), ...
    VS_true(2), ...
    VS_true(1), ...
    VS_true(1)];

vs_m = [ ...
    x_mean_dlh(4), ...
    x_mean_dlh(4), ...
    x_mean_dlh(3), ...
    x_mean_dlh(3), ...
    x_mean_dlh(2), ...
    x_mean_dlh(2), ...
    x_mean_dlh(1), ...
    x_mean_dlh(1)];

vs_ub = [ ...
    ub(4), ...
    ub(4), ...
    ub(3), ...
    ub(3), ...
    ub(2), ...
    ub(2), ...
    ub(1), ...
    ub(1)];

vs_lb = [ ...
    lb(4), ...
    lb(4), ...
    lb(3), ...
    lb(3), ...
    lb(2), ...
    lb(2), ...
    lb(1), ...
    lb(1)];

h1 = plot( ...
    vs_l, ...
    thk_l, ...
    'k', ...
    'LineWidth', 1.5);

hold on;

h2 = plot( ...
    vs_ub, ...
    thk_ub, ...
    '--k', ...
    'LineWidth', 1);

h3 = plot( ...
    vs_lb, ...
    thk_lb, ...
    '--k', ...
    'LineWidth', 1);

h4 = plot( ...
    vs_m, ...
    thk_m, ...
    '--r', ...
    'LineWidth', 1.5);

axis([ ...
    0, ...
    max(ub(1:5)) + 50, ...
    0, ...
    max([X_l, max(thk_b), max(thk_m)])]);

axis ij;

xlabel( ...
    'Shear-wave velocity (m/s)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

ylabel( ...
    'Depth (m)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

legend( ...
    [h1, h2, h3, h4], ...
    { ...
        'True model', ...
        'Upper parameter bound', ...
        'Lower parameter bound', ...
        'Mean inverted model' ...
    }, ...
    'Location', 'northeast', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10);

set( ...
    gca, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

requiredVars = { ...
    'Npop', ...
    'Max_it', ...
    'Nrun', ...
    'nD', ...
    'lb', ...
    'ub', ...
    'VS_true', ...
    'VP_true', ...
    'H_true', ...
    'den', ...
    'x_all_dlh', ...
    'x_mean_dlh', ...
    'x_best_dlh', ...
    'f_all_dlh', ...
    'hist_all_dlh', ...
    'idx_best', ...
    'freq', ...
    'pv', ...
    'pv_true', ...
    'pv_mean'};

for iVar = 1:numel(requiredVars)

    if ~exist(requiredVars{iVar}, 'var')
        error( ...
            'Required variable "%s" does not exist.', ...
            requiredVars{iVar});
    end
end

if numel(freq) ~= numel(pv)
    error( ...
        'freq and pv have different lengths: freq=%d, pv=%d.', ...
        numel(freq), ...
        numel(pv));
end

if numel(freq) ~= numel(pv_true)
    error( ...
        ['freq and pv_true have different lengths: ', ...
         'freq=%d, pv_true=%d.'], ...
        numel(freq), ...
        numel(pv_true));
end

if numel(freq) ~= numel(pv_mean)
    error( ...
        ['freq and pv_mean have different lengths: ', ...
         'freq=%d, pv_mean=%d.'], ...
        numel(freq), ...
        numel(pv_mean));
end

if size(hist_all_dlh, 1) ~= Nrun || ...
        size(hist_all_dlh, 2) ~= Max_it

    error( ...
        ['Incorrect hist_all_dlh size. Current size is %d-by-%d; ', ...
         'expected size is %d-by-%d.'], ...
        size(hist_all_dlh, 1), ...
        size(hist_all_dlh, 2), ...
        Nrun, ...
        Max_it);
end

result_3p = struct();

result_3p.methodName = 'Three-parameter inversion';
result_3p.parameterMode = 'Vs-H-Vp inversion';

result_3p.Npop = Npop;
result_3p.Max_it = Max_it;
result_3p.Nrun = Nrun;
result_3p.nD = nD;

if exist('n_mode', 'var')
    result_3p.n_mode = n_mode;
end

result_3p.lb = lb(:).';
result_3p.ub = ub(:).';

result_3p.VS_true = VS_true(:).';
result_3p.VP_true = VP_true(:).';
result_3p.H_true = H_true(:).';
result_3p.den = den(:).';

result_3p.x_all = x_all_dlh;
result_3p.x_mean = x_mean_dlh(:).';
result_3p.x_best = x_best_dlh(:).';

result_3p.f_all = f_all_dlh(:);
result_3p.f_best = min(f_all_dlh);
result_3p.idx_best = idx_best;

result_3p.hist_all = hist_all_dlh;

result_3p.hist_mean = mean( ...
    hist_all_dlh, ...
    1, ...
    'omitnan');

result_3p.hist_median = median( ...
    hist_all_dlh, ...
    1, ...
    'omitnan');

result_3p.iteration = 1:Max_it;

result_3p.freq = freq(:);
result_3p.pv_obs = pv(:);
result_3p.pv_true = pv_true(:);
result_3p.pv_mean = pv_mean(:);

save('result_3pmn.mat', 'result_3p');